import swaggerAutogen from 'swagger-autogen';

const doc = {
  info: {
    title: 'Lattice API',
    version: '1.0.0',
    description: 'Auto-generated by swagger-autogen'
  },
  host: 'localhost:3000',
  schemes: ['http']
};

const outputFile = './src/swagger-output.json';
const endpointsFiles = [
  './src/dev.ts',
  './src/core/http/api/auth.ts',
  './src/core/http/api/users.ts',
  './src/core/http/api/permissions.ts',
  './src/core/http/api/contexts.ts',
  './src/core/http/api/roles.ts'
];

const generate = swaggerAutogen({ openapi: '3.0.0' });

generate(outputFile, endpointsFiles, doc);
